added lab09
PdxCodeGuild/class_orchid pull request #110
Opened 2022-07-21 00:53 UTC by NSJen

Completed lab 9

2022-07-22 19:16 UTC, chapman311 approved these changes
Great job Jen! I really like the use of `.extend()` and `.sort()`. Very concise and efficient code. :)

2022-07-22 19:28 UTC, chapman311 requested changes
Hi Jen, I actually made a mistake approving this lab as completed. Looking back at the [Lab 9 instructions](https://github.com/PdxCodeGuild/class_orchid/blob/main/1%20Python/labs/09%20Peaks%20And%20Valleys.md) it specifically asks for 3 functions to be defined in the code, which are not present in your solution. The functions are to be named `peaks`, `valleys`, and `peaks_and_valleys`.

Please re-work the code to adhere to these instructions.

2022-07-22 23:26 UTC, chapman311 approved these changes
Looks great! Thank you for making those changes. :)

2022-07-26 18:56 UTC, pjz987 approved these changes

2022-07-26 18:56 UTC, merged