Vel/python/lab09
PdxCodeGuild/class_orchid pull request #116
Opened 2022-07-21 22:37 UTC by Velshaun

2022-07-22 19:20 UTC, chapman311 requested changes
Output does not give what Lab 9 asks for. Please look back at the lab instructions.

2022-07-25 23:58 UTC, Velshaun commented
I was returning the list item instead of the index. Problem solved!

2022-07-26 19:09 UTC, chapman311 approved these changes
Code looks great. I really like the protection from looping over the 0 and last index positions in your for loops. Good job with the change to record the index position too!

2022-07-26 19:10 UTC, chapman311 commented on code/vel/python/lab09_ver1.py
> +#IndexError index out of range
In the future, try to clean up these kinds of troubleshooting/coding comments before submitting.

2022-07-26 19:14 UTC, pjz987 approved these changes

2022-07-26 19:14 UTC, merged