01lab conversion
PdxCodeGuild/class_orchid pull request #19
Opened 2022-07-12 23:26 UTC by Velshaun

2022-07-13 21:17 UTC, MattDWalsh requested changes
Check your output on this - it's missing a step. Right now it's converting any input to 1 user_input_units in meters (e.g. entering 3 feet to yards returns 0.3048, or the value of 1 foot in meters).

I like how it's put together, but there's one more step!

2022-07-15 16:48 UTC, MattDWalsh approved these changes
Nice work!

2022-07-15 16:49 UTC, Velshaun commented
Thanks!

On Fri, Jul 15, 2022 at 11:48 MattDWalsh ***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> Nice work!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/PdxCodeGuild/class_orchid/pull/19#pullrequestreview-1040553667>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZXGT6P2S5OWFMHHZAXKPMLVUGI6XANCNFSM53MVIQDQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-07-15 21:57 UTC, pjz987 approved these changes

2022-07-15 21:57 UTC, merged