Lab01, I still think Elon is a fun guy
PdxCodeGuild/class_orchid pull request #226
Opened 2022-08-18 17:14 UTC by JordynHolder

2022-08-18 19:23 UTC, chapman311 requested changes
Please read through the lab requirements and ensure all parts have been acheived. I think the following need to be addressed:

- Center the entire content of the body
- Use a custom font
- Add a background image
- Pick a color scheme and modify the background, body text, and link text color.

Additionally, the use of flexbox or grid to prevent the image from overlapping the text would be nice.

2022-08-24 20:43 UTC, chapman311 requested changes
Page is looking better! Part two of the lab does specifically state that a background image should be added, which is missing on this page. 

Additionally, the lab say "Center the entire content of the body", I would say that the centering of the body is not really working. I can see that there is `justify-content: center` in the CSS, I am just not sure it is achieving the desired effect. 

If, at least, the background image can be added, I would say this is meeting the minimum requirements of Lab 1.

2022-08-24 23:08 UTC, JordynHolder commented
I mistook the second comment for the first one since I was having some git issues earlier this morning. Thanks for feedback I will fix that shortly.

2022-08-24 23:34 UTC, chapman311 approved these changes

2022-09-02 17:20 UTC, merged