Chirp Lab completed
PdxCodeGuild/class_orchid pull request #285
Opened 2022-09-14 01:52 UTC by cesrebol

2022-09-14 21:12 UTC, MattDWalsh requested changes
This is great so far, but it's missing the "profile view" (a list of all chirps by a user). Add that and you'll be set!

2022-09-14 22:39 UTC, cesrebol commented
@MattDWalsh Hey Matt! I made the changes you have requested. Thanks again!

2022-09-16 18:35 UTC, MattDWalsh commented on code/cesar/django/lab_03/chirp/chirp/urls.py
> +    path('users/', include('users.url')),
Check this line!

2022-09-16 18:36 UTC, MattDWalsh requested changes
You are literally ONE character away from this being done! Check line 24 in your _project_ urls.py.

2022-09-19 21:33 UTC, cesrebol commented
@Gage-Lieble Hi Gage, I have fixed the type Matt found. Could you check this out when you get the chance? Thanks!

2022-09-19 21:41 UTC, Gage-Lieble commented
Looks good!

2022-09-19 22:12 UTC, merged