Tony/python/lab02
PdxCodeGuild/class_orchid pull request #42
Opened 2022-07-13 23:22 UTC by webavant

2022-07-13 23:25 UTC, chapman311 requested changes
First part of Lab 2 is missing.

Please revise the 'lab02.py' to include the version 1 code, above the version 2 code; with comments in the code for which is which.
OR
Preferably, there can be a separate file for each version of the lab: 'lab02_ver1.py' and 'lab02_ver2.py'

2022-07-13 23:27 UTC, webavant commented
Ah, my bad! I made commits for each version, assuming that was how you'd prefer it.

2022-07-14 21:15 UTC, chapman311 commented on code/tony/python/lab02_version1.py
> +nums = list()
This is an empty list. It is also an interesting way to insatiate a list. Instead you can just say `nums = []`

2022-07-14 21:16 UTC, chapman311 submitted a review, later dismissed
Version 1 is giving a ZeroDivisionError, and appears to be missing some values in the `nums` list.

2022-07-14 21:17 UTC, chapman311 commented on code/tony/python/lab02_version2.py
> +    print(int(avg))
Type-casting the `avg` to an `int` here is not producing the correct average.

2022-07-15 16:57 UTC, chapman311 requested changes
Version 1 has a minor error resulting in an incorrect output of the average when the average has decimal places. Version 2 does not have this error,

2022-07-15 16:57 UTC, chapman311 commented on code/tony/python/lab02_version1.py
>  print(int(avg))
avg = 3.85714
Your code is type-casting the `avg` to an int, which rounds it to 4; producing an incorrect output.

2022-07-20 19:16 UTC, chapman311 approved these changes
Code looks good. Thank you for making those changes.

2022-07-21 19:29 UTC, merged