commit lab 05
PdxCodeGuild/class_orchid pull request #62
Opened 2022-07-14 22:03 UTC by Krystah

Good Afternoon, Please pull Lab05. Thank You!

2022-07-19 20:40 UTC, MattDWalsh requested changes
Nice work so far! Version 1 is very close to being done, but you have a typo that's causing an error in some circumstances. Check a variety of inputs and look at what happens to spot it.

Version 2 isn't done yet, but based on your commit message I think you already know that!

2022-07-22 17:14 UTC, MattDWalsh requested changes
V1 is complete, thanks for fixing that variable name and syntax issue!

One last minor change: please remove V2 from the branch and commit/push again. You can put that file on another branch if you'd like to have the opportunity to work on it later, but we only want to merge working code. Thanks!

2022-07-25 16:58 UTC, MattDWalsh approved these changes
Thank you!

2022-07-26 18:29 UTC, pjz987 approved these changes

2022-07-26 18:29 UTC, merged